language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - develop

before_script:
  - npm install -g ng-tailwindcss
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g workbox-cli

script:
  - ng-tailwindcss build
  - ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer

after_success:
  - workbox injectManifest
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change