language: node_js
node_js:
  - "6.11.1"

branches:
  only:
    - develop

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change